parameters:
#    root_accez_basic.example.class: RootAccez\BasicBundle\Example

services:
#    root_accez_basic.example:
#        class: %root_accez_basic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
